### ISSUE TITLE
Feature requests: 1. comment out whole subtree, 2. Evaluate subtree

### ISSUE THREAD

**Issue by priyadarshan** [tj64/outshine#61] opened 2016-04-16 13:19 UTC
Outshine has become for me an indispensable asset in my toolchain.

I find myself wishing again and again for two features, would you consider adding them?

1. Comment (and uncomment) a whole subtree (same as :tangle no in org mode's babel block)

2. Evaluate subtree (same as C-c C-c while within a org-mode's babel block)

Thank you so much for `outshine`, it has made coding so much more fun.

**Comment by tj64** [comment] 2016-04-16 14:24
Hi, thanks for the kind words!

Do you use navi-mode together with outshine? 
It already offers these features, at least almost:

 2) Eval Subtree
Say you want to eval a level 3 subtree:

   - type 3 in navi buffer
   - navi(gate) to subtree
   - type , (i.e. a comma)
   - enter function "eval-region"
   - enter arg "nil"

and the (marked) subtree will be evaluated 
Try C-h f navi-act-on-thing-at-point for more info.

1) comment whole subtree
you can do the same as above and use function "comment-region", and it almost does what you want. Almost, because not only the content, but also the headline is outcommented, what causes troubles afterwards.

You can mark a subtree as (org) comment using outshine-toggle-comment (or navi-toggle-comment).

Your best bet right now would be the following use-case with navi-mode:
  
   1. navi(gate) to target subtree
   2. press m (subtree will be marked, point moves to beginning of marked subtree in programming-mode buffer) 
   3. do C-n (i.e. move one line down)
   4. do M-; (i.e. comment-dwim) 

For uncommenting the subtree again, do exactly the same.

**Comment by priyadarshan** [comment] 2016-04-16 15:11
Thank you very much for the detail answer.

I can make a keyboard macro to deal with commenting a subtree.

The missing thing from evaluating a subtree like that is that no return value seems to be displayed.

Let's say one has,

```
;;; Test
(message "Done")

;;; Test 2
(message "Done 2")
```
If I `eval-region` the first subtree, I will get "Done" in the minibuffer and in the Messages buffer.

But if I do it with `outshine-navi`, then `,` `eval-region` `nil`, nothing seems to be displayed.

Thank you once again for `outshine` and `navi-mode`, they are addictive!

**Comment by tj64** [comment] 2016-04-16 15:32
I just added two convenience functions to trunk and pushed them:

- outshine-eval-lisp-subtree
- outshine-comment-subtree-content

Please try them out, do they work as intended?

**Comment by priyadarshan** [comment] 2016-04-16 15:41
Wow, perfect! :tada: 
Thank you so much for the new features, much obliged.

**Comment by tj64** [comment] 2016-04-16 15:45
You are welcome ;-)
So I close this thread now, and merge the new stuff into master, hoping that I had no good reason to outcomment the bugfix for the erratic behaviour before.

**Closed by tj64** 2016-04-16 15:45 UTC

**Comment by priyadarshan** [comment] 2016-04-16 15:57
Thank you. At one point you may want to add a line to the README, for those two new features, as they are really nice, and people may want to know. I will continue using `outhsine` and `navi-mode`, and report back in case I see anything unusual.

Cheerio.
